<a href="https://colab.research.google.com/github/EAsencios/DEEP-LEARING/blob/master/fea_eng_binarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import scipy.stats as spstats

In [4]:
mpl.style.reload_library()
mpl.style.use('classic')
mpl.rcParams['figure.facecolor'] = (1, 1, 1, 0)
mpl.rcParams['figure.figsize'] = [6.0, 4.0]
mpl.rcParams['figure.dpi'] = 100

In [17]:
popsong_df = pd.read_csv('/content/sample_data/song_views.csv')
popsong_df.head(10)

                                    user_id  ... listen_count
0  b6b799f34a204bd928ea014c243ddad6d0be4f8f  ...            2
1  b41ead730ac14f6b6717b9cf8859d5579f3f8d4d  ...            0
2  4c84359a164b161496d05282707cecbd50adbfc4  ...            0
3  779b5908593756abb6ff7586177c966022668b06  ...            0
4  dd88ea94f605a63d9fc37a214127e3f00e85e42d  ...            0
5  68f0359a2f1cedb0d15c98d88017281db79f9bc6  ...            0
6  116a4c95d63623a967edf2f3456c90ebbf964e6f  ...           17
7  45544491ccfcdc0b0803c34f201a6287ed4e30f8  ...            0
8  e701a24d9b6c59f5ac37ab28462ca82470e27cfb  ...           68
9  edc8b7b1fd592a3b69c3d823a742e1a064abec95  ...            0

[10 rows x 4 columns]

In [20]:
watched = np.array(popsong_df['listen_count'])
watched[watched >= 1] = 1
popsong_df['watched'] = watched
popsong_df

                                      user_id  ... watched
0    b6b799f34a204bd928ea014c243ddad6d0be4f8f  ...       1
1    b41ead730ac14f6b6717b9cf8859d5579f3f8d4d  ...       0
2    4c84359a164b161496d05282707cecbd50adbfc4  ...       0
3    779b5908593756abb6ff7586177c966022668b06  ...       0
4    dd88ea94f605a63d9fc37a214127e3f00e85e42d  ...       0
..                                        ...  ...     ...
360  42c9fba813dd9ca8ca3673277a0f923b6845a7a6  ...       0
361  3f152d355d53865a2ca27ac5ceeffb7ebaea0a26  ...       0
362  b4adf5ac8bcba59011df7be840dda1134a47cc30  ...       0
363  8f241c98c6cc95ab4a8260ff9b510c2e445a33d7  ...       0
364  7d9b58502405c5bbbfff0c5683cb2dea71089908  ...       0

[365 rows x 5 columns]